#!/bin/bash

###########
#
# SETTING UP COLLORS
#
###########

red='\e[0;31m'
RED='\e[1;31m'
org='\e[0;33m33'
blue='\e[0;34m'
BLUE='\e[1;34m'
cyan='\e[0;36m'
CYAN='\e[1;36m'
GRN='\e[0;32m'
NC='\e[0m'

###########
#
# INSTALLING G++
#
###########

echo -e "\n${GRN}NOW TRYING TO INSTALL G++${NC}\n\n"

if [ -f /usr/bin/yum ];
then
   yum install gcc-c++ compat-gcc-34 compat-gcc-34-c++ -y >> /dev/null
fi

if [ -f /usr/bin/apt-get ];
then
   apt-get update >> /dev/null
   apt-get install g++ -y >> /dev/null
fi

if [ -f /usr/include/stdio.h ]; then
echo -e "${BLUE}G++ INSTALL${NC}            [ ${GRN}COMPLETED${NC} ]"
else
echo -e "${BLUE}G++ INSTALL${NC}            [ ${RED}INCOMPLETED${NC} ]"
fi
